portfolio-site/contact/urls.py
from django.urls import path
from .import views

app_name = 'contact'
urlpatterns = [
    path('', views.ContactFormView.as_view(), name='contact'),
    path('success/', views.ContactSuccessView.as_view(), name='success'),
]

portfolio-site/homepage/urls.py
from django.urls import path
from .import views

app_name = 'homepage'
urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
]

portfolio-site/portfolio/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('homepage.urls')),
    path('projects/', include('projects.urls')),
    path('contact/', include('contact.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

portfolio-site/projects/urls.py
from django.urls import path
from .import views

app_name = 'projects'
urlpatterns = [
    path('', views.ProjectsView.as_view(), name='projects'),
]

portfolio-site/contact/models.py
from django.db import models

# Create your models here.

portfolio-site/homepage/models.py
from django.db import models

class HomePage(models.Model):
    header = models.CharField(max_length=100, null=True)
    headshot = models.ImageField(blank=True, upload_to='home_images')
    bio = models.TextField(max_length=1000)

portfolio-site/projects/models.py
from django.db import models
from django.contrib import admin

class Project(models.Model):
    slug = models.SlugField(null=True, blank=True)
    project_name = models.CharField(max_length=100, null=True)
    project_screenshot = models.ImageField(blank=True, upload_to='project_images')
    project_details = models.TextField(max_length=500)
    github_link = models.URLField(null=True)
    gitlab_link = models.URLField(null=True)
    pub_date = models.DateTimeField('date published')

    @admin.display(
        boolean=True,
        ordering='pub_date',
        description='Published recently?',
    )

    def __str__(self):
        return self.project_name

portfolio-site/contact/forms.py
from django import forms
from django.conf import settings
from django.core.mail import send_mail

class ContactForm(forms.Form):
    name = forms.CharField(label=False, max_length=100)
    email = forms.EmailField(label=False, max_length=100)
    subject = forms.CharField(label=False, max_length=100)
    message = forms.CharField(label=False, widget=forms.Textarea)

    def get_info(self):
        """Method that returns formatted information
        :return: subject, msg
        """

        # Cleaned data
        cl_data = super().clean()

        name = cl_data.get('name').strip()
        from_email = cl_data.get('email')
        subject = cl_data.get('subject')

        msg = f'{name} with email {from_email} said:'
        msg += f'\n\n"Subject: {subject}"\n\n'
        msg += cl_data.get('message')

        return subject, msg

    def send(self):

        subject, msg = self.get_info()

        send_mail(
            subject=subject,
            message=msg,
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[settings.RECIPIENT_ADDRESS]
        )

portfolio-site/contact/views.py
from django.views.generic import FormView, TemplateView
from django.urls import reverse_lazy

from .forms import ContactForm

class ContactFormView(FormView):
    template_name = 'contact/base_contact.html'
    form_class = ContactForm
    success_url = reverse_lazy('contact:success')

    def form_valid(self, form):
        # This method is called when valid form data has ben POSTed.
        # It should return an HttpResponse.
        form.send()
        return super().form_valid(form)

class ContactSuccessView(TemplateView):
    template_name = 'contact/base_contact_success.html'

portfolio-site/homepage/views.py
from homepage.models import HomePage
from django.views import generic

class HomePageView(generic.ListView):
    template_name = "homepage/base_home.html"
    context_object_name = 'latest_homepage'

    def get_queryset(self):
        """Return the most recent HomePage Object"""
        return HomePage.objects.all()

portfolio-site/projects/views.py
from .models import Project
from django.views import generic
from django.utils import timezone

class ProjectsView(generic.ListView):
    template_name = 'projects/base_project.html'
    context_object_name = 'latest_project_list'

    def get_queryset(self):
        """Return the last five published projects,
        not including those set to be published 
        in the future."""
        return Project.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')

portfolio-site/contact/templates/contact/base_contact.html
{% extends "base.html" %}
{% block title %}Contact{% endblock %}

{% block content %}
<div class="container">
	<div class="row justify-content-md-center">
		<h1>Contact Brandon</h1>
	</div>
	<div class="row justify-content-md-center">
		<p><small>If you have any business inquiries, please fill out this form and I will respond as soon as possible. Thank you!</small></p>
	</div>
	</br>
	<form action="/contact/" method="post">
		{% csrf_token %}
		<div class="row justify-content-md-center">
			<div class="col-5">
				{{ form.name }}
			</div>
			<div class="col-5">
				{{ form.email }}
			</div>
		</div>
		</br>
		<div class="row justify-content-md-center">
			<div class="col-10">
				{{ form.subject }}
			</div>
		</div>
		</br>
		<div class="row justify-content-md-center">
			<div class="col-10">
				{{ form.message }}
			</div>
		</div>
		</br>
		<div class="row justify-content-md-center">
			<div class="col-10">
				<button class="btn btn-lg" type="submit"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-envelope" viewBox="0 0 20 20">
  <path d="M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V4zm2-1a1 1 0 0 0-1 1v.217l7 4.2 7-4.2V4a1 1 0 0 0-1-1H2zm13 2.383-4.758 2.855L15 11.114v-5.73zm-.034 6.878L9.271 8.82 8 9.583 6.728 8.82l-5.694 3.44A1 1 0 0 0 2 13h12a1 1 0 0 0 .966-.739zM1 11.114l4.758-2.876L1 5.383v5.73z"/>
</svg> Send Message</button>
			</div>
		</div>
	</form>
</div>
		<footer class="bd-footer py-5 mt-5 fixed-bottom" id="footer">
			<div class="footer-copyright">
				<p class="text-center"><small>The code of this site is Copyright 2021 Brandon T. Phillips. 
				</br>
				It is 
				<a rel="source-code-link" href="https://github.com/brandontdev/portfolio-site">free and open source software</a> 
				available under the terms of the 
				<a rel="code-license-link" href="https://github.com/brandontdev/portfolio-site/blob/main/LICENSE.md">GNU GPL Version 3</a>.
				</br>
				The design of this site is Copyright 2021 Brandon T. Phillips. 
				</br>It is available under the terms of the 
				<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">
				Creative Commons Attribution-ShareAlike 4.0 International License
				</a>
				</small></p>
			</div>
		</footer>

{% endblock %}

portfolio-site/contact/templates/contact/base_contact_success.html
{% extends "base.html" %}
{% block title %}Success{% endblock %}

{% block content %}
	<h1>Thank you for reaching out!</h1>
	<p>You can send another in the <a href="{% url 'contact:contact' %}">contact page</a></p>
		<footer class="bd-footer py-5 mt-5 fixed-bottom" id="footer">
			<div class="footer-copyright">
				<p class="text-center"><small>The code of this site is Copyright 2021 Brandon T. Phillips. 
				</br>
				It is 
				<a rel="source-code-link" href="https://github.com/brandontdev/portfolio-site">free and open source software</a> 
				available under the terms of the 
				<a rel="code-license-link" href="https://github.com/brandontdev/portfolio-site/blob/main/LICENSE.md">GNU GPL Version 3</a>.
				</br>
				The design of this site is Copyright 2021 Brandon T. Phillips. 
				</br>It is available under the terms of the 
				<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">
				Creative Commons Attribution-ShareAlike 4.0 International License
				</a>
				</small></p>
			</div>
		</footer>

{% endblock %}

portfolio-site/homepage/templates/homepage/base_home.html
{% extends "base.html" %}
{% block title %}Brandon's homepage{% endblock %}

{% block content %}
	{% if latest_homepage %}
		<div class="container">
		{% for homepage in latest_homepage %}
			<div class="row gy-5 justify-content-md-center">
				<div class="col-5">
					<img src="{{ homepage.headshot.url }}" class="img-fluid rounded">
				</div>
			</div>
			</br>
			<div class="row gy-5 justify-content-md-center">
				<div class="col-10">
					<h1 class ="display-1" style="text-align: center">{{ homepage.header }}</h1>
				</div>
				<div class="col-7">
					<p style="text-align: center">{{ homepage.bio }}</p>
				</div>
			</div>
			</br>
			</br>
			<div class="row gy-5 my-5 justify-content-md-center">
				<div class="col-3 d-flex justify-content-center">
					<button type="button" class="btn btn-lg" onclick="window.location.href='/projects/'">
						<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-code" viewBox="0 0 16 16">
  <path d="M5.854 4.854a.5.5 0 1 0-.708-.708l-3.5 3.5a.5.5 0 0 0 0 .708l3.5 3.5a.5.5 0 0 0 .708-.708L2.707 8l3.147-3.146zm4.292 0a.5.5 0 0 1 .708-.708l3.5 3.5a.5.5 0 0 1 0 .708l-3.5 3.5a.5.5 0 0 1-.708-.708L13.293 8l-3.147-3.146z"/>
</svg>						
						My Work</button>
				</div>
				<div class="col-3 d-flex justify-content-center">
					<button type="button" class="btn btn-lg" onclick="window.location.href='/contact/'">
						<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-envelope" viewBox="0 0 20 20">
  <path d="M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V4zm2-1a1 1 0 0 0-1 1v.217l7 4.2 7-4.2V4a1 1 0 0 0-1-1H2zm13 2.383-4.758 2.855L15 11.114v-5.73zm-.034 6.878L9.271 8.82 8 9.583 6.728 8.82l-5.694 3.44A1 1 0 0 0 2 13h12a1 1 0 0 0 .966-.739zM1 11.114l4.758-2.876L1 5.383v5.73z"/>
</svg> 
						Contact Me</button>
				</div>
			<footer class="bd-footer py-5 mt-5 fixed-bottom" id="footer">
				<div class="footer-copyright">
					<p class="text-center"><small>The code of this site is Copyright 2021 Brandon T. Phillips. 
					</br>
					It is 
					<a rel="source-code-link" href="https://github.com/brandontdev/portfolio-site">free and open source software</a> 
					available under the terms of the 
					<a rel="code-license-link" href="https://github.com/brandontdev/portfolio-site/blob/main/LICENSE.md">GNU GPL Version 3</a>.
					</br>
					The design of this site is Copyright 2021 Brandon T. Phillips. 
					</br>It is available under the terms of the 
					<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">
					Creative Commons Attribution-ShareAlike 4.0 International License
					</a>
					</small></p>
				</div>
			</footer>
		</div>
		{% endfor %}
	{% endif %}
{% endblock %}

portfolio-site/portfolio/templates/base.html
<!DOCTYPE html>
{% load bootstrap4 %}
{% load static %}
<html lang="en">
<head>
	{% bootstrap_css %}
	{% bootstrap_javascript jquery='full' %}
	<link rel="stylesheet" type="text/css" href="bootstrap.min.css">
	<link href="{% static 'fontawesome_free/css/all.min.css' %}" rel="stylesheet" type="text/css">
	<link rel="stylesheet" type='text/css' href="{% static 'portfolio/custom.css' %}">
	<script scr="{% static 'fontawesome_free/js/all.min.js' %}"></script>
	<title>{% block title %}Brandon's site{% endblock %}</title>
</head>

<div class="container pt-3 w-100" id="body">
<body>

	<!--Top Navbar-->
	<nav class="navbar navbar-expand-sm navbar-dark">
		{% block nav-bar %}
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarText">
			<ul class="navbar-nav mr-auto">
				<li class="nav-item">
					<a class="nav-link" href="/">Home</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="/projects/">Projects</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="/contact/">Contact</a>
				</li>
			</ul>
				<span class="nav justify-content-end">
					<li class="nav-item">
						<a class="nav-link" href="https://twitter.com/dontbran"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-twitter" viewBox="0 0 16 16">
    	  	  	<path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"/>
						</svg></a></li>
						<li class="nam-item">
					<a class="nav-link"  href="https://www.twitch.tv/brandontdev"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-twitch" viewBox="0 0 16 16">
  	      	<path d="M3.857 0 1 2.857v10.286h3.429V16l2.857-2.857H9.57L14.714 8V0H3.857zm9.714 7.429-2.285 2.285H9l-2 2v-2H4.429V1.143h9.142v6.286z"/>
    	      <path d="M11.857 3.143h-1.143V6.57h1.143V3.143zm-3.143 0H7.571V6.57h1.143V3.143z"/>
							</svg></a></li>
					<li class="nav-item">
						<a class="nav-link"  href="https://github.com/brandontdev"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-github" viewBox="0 0 16 16">
			  		<path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"/>
						</svg></a></li>
				</span>
				</ul>
			</ul>
		</div>
	</nav>
		{% endblock %}

	<div class="container pt-5" id="main-content">
		{% block content %}
		{% endblock %}
	</div>
</body>
</div>
</html>

portfolio-site/portfolio/templates/django/forms/widgets/input.html
<input class="form-control" placeholder="Enter {{ widget.name }}"type="{{ widget.type }}" name="{{ widget.name }}"{% if widget.value != None %} value="{{ widget.value|stringformat:'s' }}"{% endif %}{% include "django/forms/widgets/attrs.html" %}>

portfolio-site/portfolio/templates/django/forms/widgets/textarea.html
<textarea class="form-control" name="{{ widget.name }}"{% include "django/forms/widgets/attrs.html" %} placeholder="Enter your message here.">
{% if widget.value %}{{ widget.value }}{% endif %}</textarea>

portfolio-site/projects/templates/projects/base_project.html
{% extends "base.html" %}
{% block title %}Brandon's Portfolio{% endblock %}

{% block content %}
	{% if latest_project_list %}
		<div class="container">
			<ul>
			{% for project in latest_project_list %}
			<div class="row gy-5 justify-content-md-center">
				<div class="col-9">
					<div class="p-3">
						<h1 class="display-5">{{ project.project_name }}</h1>
						<img src="{{ project.project_screenshot.url }}" class="img-fluid" alt="{{ project.project_name }} screenshot">
						<div class="row gy-2">
							<div class="col">
								</br>
								<p>{{ project.project_details }}</p>
							</div>
						</div>
							<ul class="nav" id="projects-navbar">
								<li class="nav-item">
									<a class="nav-link" href="{{ project.github_link }}">
									<i class="fab fa-github"></i>
										GitHub</a>
								</li>
								<li class="nav-item">
								</li>
								<li class="nav-item">
									<a class="nav-link" href="{{ project.gitlab_link }}">
									<i class="fab fa-gitlab"></i>
										GitLab</a>
								</li>
							</ul>
					</div>
				</div>
			</div>
			</br>
			{% endfor %}
			</ul>
		</div>
	{% else %}
		<h2>No projects are available</h2>
	{% endif %}
		<footer class="bd-footer py-5 mt-5" id="footer">
			<div class="footer-copyright">
				<p class="text-center"><small>The code of this site is Copyright 2021 Brandon T. Phillips. 
				</br>
				It is 
				<a rel="source-code-link" href="https://github.com/brandontdev/portfolio-site">free and open source software</a> 
				available under the terms of the 
				<a rel="code-license-link" href="https://github.com/brandontdev/portfolio-site/blob/main/LICENSE.md">GNU GPL Version 3</a>.
				</br>
				The design of this site is Copyright 2021 Brandon T. Phillips. 
				</br>It is available under the terms of the 
				<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">
				Creative Commons Attribution-ShareAlike 4.0 International License
				</a>
				</small></p>
			</div>
		</footer>
{% endblock %}